version: '3.8'

services:
  messanger:
    container_name: messanger
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./messanger", "-config", "./prod.yaml"]
    depends_on:
      - redis
      - postgres
    ports:
      - 50001:50001
    environment:
      - DB_PASSWORD=password

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    
  migrations:
    container_name: migrations
    image: migrate/migrate:latest
    depends_on:
      - postgres
    entrypoint: [ "migrate" ]
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@postgres:5432/postgres?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    networks:
      - default

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s