env: "local"

grpc:
  address: "0.0.0.0"
  port: "50001"
  request_timeout: 5s

http:
  address: "0.0.0.0"
  port: "50002"

chat:
  maximum_chats_count: 5
  messages_per_chat: 2
  chat_ttl: 30s

user:
  jwt_access_ttl: 5m
  jwt_refresh_ttl: 1h
  jwt_secret: adshasdhajsduasdjansdamzxnnzxjhahdquwendxzc82

postgres:
  host: "0.0.0.0"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "postgres"

redis:
  address: "0.0.0.0"
  port: "6379"
  password: ""
  db: 0

kafka:
  host: "0.0.0.0"
  port: "9092"