env: "prod"

grpc:
  address: "0.0.0.0"
  port: "50001"
  request_timeout: 5s

chat:
  maximum_chats_count: 5
  messages_per_chat: 2
  chat_ttl: 30s

user:
  jwt_access_ttl: 5m
  jwt_refresh_ttl: 1h
  jwt_secret: adshasdhajsduasdjansdamzxnnzxjhahdquwendxzc82

postgres:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "postgres"

redis:
  address: "redis"
  port: "6379"
  password: ""
  db: 0